[package]
name = "distance-db"
version = "0.1.0"
authors = ["Brian Bowman <seeker14491@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.9"
color-backtrace = "0.2.3"
diesel = { version = "1.4.2", features = ["chrono", "postgres"] }
distance-util = { git = "https://github.com/Seeker14491/distance-util.git", tag = "v0.0.5"}
dotenv = "0.14.1"
env_logger = "0.7.0"
failure = "0.1.5"
futures-preview = "0.3.0-alpha.19"
itertools = "0.8.0"
log = "0.4.8"
num-derive = "0.3.0"
num-traits = "0.2.8"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
serde_repr = "0.1.5"
steamworks = { git = "https://github.com/Seeker14491/steamworks-rs.git", tag = "v0.0.10" }
dunce = "1.0.0"
